### PR TITLE
Use uint instead bigint

### PR DESCRIPTION
**Pull request by dvdplm**
~~NOTE: do not merge before https://github.com/paritytech/parity-common/pull/25  and https://github.com/fckt/parity-hash/pull/9 are merged and `uint` v0.3 is published~~.

### CODE REVIEW

**Comment by sorpaas** [comment]
I think [pwasm-ethereum](https://github.com/paritytech/pwasm-ethereum/blob/master/Cargo.toml) crate will also need to be ported from `bigint` to `uint` (and possibly update `parity-hash` version as well).

**Comment by dvdplm** [comment]
@sorpaas yes, PRs are [here](https://github.com/fckt/parity-hash/pull/9) and [here](https://github.com/paritytech/pwasm-ethereum/pull/13).

**Review by andresilva — APPROVED** [review]
LGTM.

**Comment by andresilva** [comment]
https://github.com/paritytech/pwasm-ethereum/pull/13 is merged. So let's get `pwasm-ethereum` 0.6.3 published so we can re-run the tests here.

**Comment by dvdplm** [comment]
Running `./build-all.sh` works on my machine now. @sorpaas can you try too?

**Comment by sorpaas** [comment]
Yeah, it works for me as well!

**Pull request merged**
