### PR TITLE
ext::gas_left check added

### PR DESCRIPTION
**Pull request by lexfrl**
Related https://github.com/paritytech/parity-ethereum/pull/9357

### CODE REVIEW

**Comment by NikVolf** [comment]
test fail?

**Comment by lexfrl** [comment]
> test fail?

this should be merged first https://github.com/paritytech/pwasm-ethereum/pull/14

**Comment by NikVolf** [comment]
again, why updating all wasms and all gas costs?
just checkin your gasleft.wasm and leave others alone please

**Comment by lexfrl** [comment]
@NikVolf I already changed tests here https://github.com/paritytech/parity-ethereum/pull/9357

**Review by pepyakin — APPROVED** [review]

**Pull request merged**
